---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-simplenodeapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-simplenodeapp
  name: deployment-simplenodeapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-simplenodeapp
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-simplenodeapp
    spec:
      containers:
      - image: 024848453953.dkr.ecr.ap-southeast-2.amazonaws.com/ecr-repo-simplenodeapp:latest
        imagePullPolicy: Always
        name: app-simplenodeapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: ns-simplenodeapp
  name: service-simplenodeapp
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-simplenodeapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ns-simplenodeapp
  name: ingress-simplenodeapp
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-simplenodeapp
              port:
                number: 80